version: 1.0 
component: deployment 
runAs: root
env: 
    variables:        
timeoutInSeconds:  
files:  
  - source: /
    destination: /tmp/app-deploy
#steps:
#  - stepType: Command
#    name: RunCommand
#    command: tar xvf /tmp/app-deploy/artifacts.tar.gz -C /tmp/app-front
#steps:                              
#  - stepType: Command 
#    name: RunCommand
#    command: whoami
#    runAs: opc
#    timeoutInSeconds: 300
