version: 1.0 
component: deployment 
runAs: ocarun
env: 
    variables:        
timeoutInSeconds:  
files:  
  - source: /
    destination: /tmp/app-deploy                              
#steps:                              
#  - stepType: Command 
#    name: RunCommand
#    command: whoami
#    runAs: opc
#    timeoutInSeconds: 300
